### PR TITLE
Add invalid test vectors

### LINKED ISSUE #36: Adding invalid test vectors
@soatok suggested we add test vectors that are invalid, as it can help implementers make sure that they properly check everything that has to be checked.

While adding such vectors wouldn't hurt, I'm still not convinced that they are necessary. That would be very useful for e.g. group elements accepting multiple representations, to make sure that implementations only accept canonical representations.

In the case of AEADs, these vectors might be useful for testing edge cases or common implementation mistakes. A suggested example is swapping the key and the nonce, which AEGIS facilitates since they share the same size.

However, as long as we have test vectors using different values for the nonce and the key, this case is already captured.

Did I miss something?

Implementations can forget to check the tag, so we can add a vector with an invalid tag, though.

### PR DESCRIPTION
**Pull request by samuel-lucas6**
Closes #36.

- Test Vector 5: key and nonce swapped.
- Test Vector 6: bit flip at the end of the ciphertext.
- Test Vector 7: bit flip at the end of the associated data.
- Test Vector 8: bit flip at the beginning and end of the tag.

Hopefully this covers all suggestions by @soatok and @fscoto. The Test Vector 4 section was used to create them.

### CODE REVIEW

**Comment by jedisct1** [comment]
We should mention somewhere that verification must fail for these vectors.

**Comment by jedisct1** [comment]
Also we need them both for AEGIS128L and AEGIS256.

That's a lot of invalid test vectors. Too many IMHO.

**Comment by samuel-lucas6** [comment]
> We should mention somewhere that verification must fail for these vectors.

I was thinking that too, but I'm not sure about how to format that.

> Also we need them both for AEGIS128L and AEGIS256.

Sorry, I completely forgot; I'll add AEGIS128L now.

> That's a lot of invalid test vectors. Too many IMHO.

Yeah, that's my concern as well. Which would you suggest keeping? We could remove or merge 6 and 7. I can change that after adding the AEGIS128L ones.

**Comment by fscoto** [comment]
>  That's a lot of invalid test vectors. Too many IMHO.
> 
> Yeah, that's my concern as well. Which would you suggest keeping? We could remove or merge 6 and 7. I can change that after adding the AEGIS128L ones.

I'm stlil not following on the argument that there are too many test vectors. What's the concrete harm caused by having more test vectors?

> >  We should mention somewhere that verification must fail for these vectors.
> 
> I was thinking that too, but I'm not sure about how to format that.

(Bold) “This test vector is intended to test false positives. Encryption should not output the given ciphertext/tag pairs. Decryption should return an error.” for each of the invalid test vectors' sections?

**Comment by samuel-lucas6** [comment]
> I'm stlil not following on the argument that there are too many test vectors. What's the concrete harm caused by having more test vectors?

I think you can argue either way. These things should really be tested to be thorough, but having lots of test vectors could put some people off implementing the tests at all or cause some people to skip a few.

> (Bold) “This test vector is intended to test false positives. Encryption should not output the given ciphertext/tag pairs. Decryption should return an error.” for each of the invalid test vectors' sections?

Yes, including the note for each test vector is probably clearest.

**Comment by samuel-lucas6** [comment]
> (Bold) “This test vector is intended to test false positives. Encryption should not output the given ciphertext/tag pairs. Decryption should return an error.” for each of the invalid test vectors' sections?

Should the whole thing be in bold? Or should I just put **MUST** capitalised and in bold?

> This test is only for decryption. Tag verification must fail, leading to an error.

How is this wording? I don't think encryption comes into it, but let me know if I'm mistaken.

**Comment by jedisct1** [comment]
> "Encryption should not output the given ciphertext/tag pairs"

No implementation is ever going to check that the output they get *differs* from given pairs.

I think we should only mention that the vectors MUST return a "verification failed" error.

**Comment by jedisct1** [comment]
> I'm stlil not following on the argument that there are too many test vectors. What's the concrete harm caused by having more test vectors?

There's no harm, it's just uncommon.

**Comment by fscoto** [comment]
The changeset at this point is okay for me now. I think we've hashed out the core points. Any objections to merging?

**Comment by jedisct1** [comment]
LGTM!

**Pull request merged**
