### PR TITLE
Document how to use AEGIS in the context of QUIC and DTLS

### LINKED ISSUE #80: Document usage in QUIC and DTLS
Quoting John Mattsson:

> Thinking more about QUIC and DTLS 1.3 header protection, I think this should be addressed in the CFRG draft. 
> he header protection solution should reuse the current AEGIS interfaces.

### PR DESCRIPTION
**Pull request by jedisct1**
Fixes #80

### CODE REVIEW

**Comment by emanjon** [comment]
PR looks great to me.

My email address is a bit out of date. My current last name is "Preuß Mattsson". Works in markdown with triple curly brackets

OLD John Mattsson
NEW {{{John Preuß Mattsson}}}

**Comment by samuel-lucas6** [comment]
Does this definitely belong in the AEGIS draft?

**Comment by emanjon** [comment]
> Does this definitely belong in the AEGIS draft?

I would say it belongs in the draft that registers the TLS cipher suites in the TLS Cipher Suite Registry, which is currently the AEGIS draft. But it might be cleaner to move everything TLS related (including the TLS cipher suite registration) to a new draft.

**Comment by jedisct1** [comment]
@samuel-lucas6 

It immediately shows that AEGIS can be used in QUIC and DTLS, which is useful information, and can help with adoption.

Having to hunt for that information in documents that don't exist yet, or come up with ad-hoc schemes that don't interop is not ideal.

Maybe something that can be revisited before the document becomes a RFC, but I think it's good to have this information here for now.

**Review by samuel-lucas6 — APPROVED** [review]
Fair enough. Last comma can be removed but doesn't really matter. LGTM.

**Pull request merged**
